name: java-build

on:
  push:
    paths:
      - ".github/workflows/java-build.yml"
      - "java-test-project/**"
  workflow_dispatch: # manual

jobs:
  compile:
    name: compile-java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: java --version
      - run: javac HelloWorld.java
        working-directory: ./java-test-project
      - run: java HelloWorld
        working-directory: ./java-test-project
      
      
