name: java-build

on:
  push:
    paths:
      - ".github/workflows/java-build.yml"
      - "java-test-project/**"
  workflow_dispatch: # manual

jobs:
  compile:
    name: compile-java
    runs-on: ubuntu-latest
    steps:
      - run: java --version
