# This is a basic workflow to help you get started with Actions

name: test

# trigger
on:
  push:
  schedule:
    - cron: "*/5 * * * *"

# command line scripts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: sleep 5
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
